### ISSUE TITLE
Crash when rotation

### ISSUE THREAD

**Issue by wifeisblind** [mitchtabian/Dagger-Hilt-Playerground#1]
I watched the video "Fragment Constructor Injection with Hilt" and took a look at repo.
I found that there is a crash happened when rotation.

Error msg:
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.codingwithmitch.daggerhiltplayground.ui.MainFragment: could not find Fragment constructor

This is because the system tries to re-attach fragment and re-instantiate it. But the system can't find 
an empty constructor.

I also doubt that does it work to use constructor injection in fragment even if you use fragment factory?

**Comment by mitchtabian** [comment]
It's because Hilt does the injection before `onCreate` is called. This works with regular dagger when you set the factory immediately after doing the inject (before `onCreate`). 
Anyway, I thought I tested this, looking into it.

**Comment by mitchtabian** [comment]
Fixed https://github.com/mitchtabian/Dagger-Hilt-Playerground/commit/999c4c2321e13472b6fb810f723ad3912623df28
Will take down video and fix it.

**Comment by mitchtabian** [comment]
Watch [17:28](https://youtu.be/lH6n4--3R5k&t=1048s) - [22:53](https://youtu.be/lH6n4--3R5k&t=1373s) for the fix.
