### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by asdheeraj** [mitchtabian/Dagger-Hilt-Playerground#2]
Hey Mitch!
First of all thanks for uploading this great content on Hilt!
I found a bug in the HiltExt.kt class in androidTest folder.

So line number 38 in HiltExt.kt file:

**Fix:**
Instead of using commitNow, we can use commit, because if the emulator/hardware device is locked when we run the mainFragmentTest present in the MainTest.kt, it gives illegal state exception

So replacing it with commit works in all scenarios!

PR raised for the same: https://github.com/mitchtabian/Dagger-Hilt-Playerground/pull/3

**Comment by mitchtabian** [comment]
Sure I'll take your word for it
